In [2]:
import numpy as np

In [3]:
a = np.array([1,3,4,56,7,8,np.NAN])

### 统计

In [4]:
a.sum()

nan

In [5]:
np.nansum(a) # 忽略nan求和

79.0

In [7]:
f = np.ones(7)
f[::2] = -1
f

array([-1.,  1., -1.,  1., -1.,  1., -1.])

In [9]:
b = np.random.randint(0,10,size = 7)

In [12]:
np.corrcoef(b,f) # 相关性系数

array([[ 1.        , -0.86485684],
       [-0.86485684,  1.        ]])

              b    f
    b         1    -0.86485684   

    f       -0.86485684  1

In [13]:
nd = np.random.randint(0,100,size=100)

In [14]:
np.histogram(nd,bins=10)  # 直方图，bins表示分成的份数

(array([12, 10, 10,  6, 12, 14, 12,  8, 11,  5], dtype=int64),
 array([ 0. ,  9.8, 19.6, 29.4, 39.2, 49. , 58.8, 68.6, 78.4, 88.2, 98. ]))

    第一行是出现的次数
    第二行是数据范围

In [16]:
np.histogram(nd,bins=5,range=[0,120]) # range是规定横坐标范围的

(array([26, 23, 30, 20,  1], dtype=int64),
 array([  0.,  24.,  48.,  72.,  96., 120.]))

### IO操作

In [17]:
np.save('data.npy',nd) # 保存为np
二进制形式，.npy后缀

In [18]:
np.load('data.npy') # 读取数据

array([63, 48, 66, 13, 53, 70, 86, 68, 35, 69, 95, 53, 46, 80, 41, 93, 19,
        1, 68, 56, 57, 13, 28, 25, 49,  1, 46, 73, 25, 45, 68, 16, 98, 23,
       20, 78, 39, 19, 58, 10, 45,  5, 23, 87, 58, 18,  4, 59,  9, 22,  0,
       71,  8, 63, 60, 54, 80, 46, 84, 57, 14, 58, 90, 27, 46, 12, 68, 31,
       87, 42, 34, 62, 94, 25, 43, 87,  3, 54, 63, 52,  7,  0, 73, 75,  5,
       83,  7, 86, 25, 64, 35, 85, 79, 76, 41, 51, 35, 16, 51, 41])

In [20]:
np.savetxt('data.txt',nd) # 保存为txt形式，默认科学计数法保存

In [21]:
np.loadtxt('data.txt') 

array([63., 48., 66., 13., 53., 70., 86., 68., 35., 69., 95., 53., 46.,
       80., 41., 93., 19.,  1., 68., 56., 57., 13., 28., 25., 49.,  1.,
       46., 73., 25., 45., 68., 16., 98., 23., 20., 78., 39., 19., 58.,
       10., 45.,  5., 23., 87., 58., 18.,  4., 59.,  9., 22.,  0., 71.,
        8., 63., 60., 54., 80., 46., 84., 57., 14., 58., 90., 27., 46.,
       12., 68., 31., 87., 42., 34., 62., 94., 25., 43., 87.,  3., 54.,
       63., 52.,  7.,  0., 73., 75.,  5., 83.,  7., 86., 25., 64., 35.,
       85., 79., 76., 41., 51., 35., 16., 51., 41.])

 ### 矩阵运算

x + y + z = 8
2x - y + z = 8
3x + y - z = 2

In [23]:
X = np.array([[1,1,1],[2,-1,1],[3,1,-1]])
X

array([[ 1,  1,  1],
       [ 2, -1,  1],
       [ 3,  1, -1]])

In [25]:
Y = np.array([8,8,2])
Y

array([8, 8, 2])

In [26]:
# x逆矩阵
X_inv = np.linalg.inv(X)
X_inv

array([[ 0. ,  0.2,  0.2],
       [ 0.5, -0.4,  0.1],
       [ 0.5,  0.2, -0.3]])

In [27]:
np.dot(X_inv,Y)  # 矩阵点积

array([2., 1., 5.])

     所得的结果即为xyz对应取值

  ###  广播机制

In [28]:
nd

array([63, 48, 66, 13, 53, 70, 86, 68, 35, 69, 95, 53, 46, 80, 41, 93, 19,
        1, 68, 56, 57, 13, 28, 25, 49,  1, 46, 73, 25, 45, 68, 16, 98, 23,
       20, 78, 39, 19, 58, 10, 45,  5, 23, 87, 58, 18,  4, 59,  9, 22,  0,
       71,  8, 63, 60, 54, 80, 46, 84, 57, 14, 58, 90, 27, 46, 12, 68, 31,
       87, 42, 34, 62, 94, 25, 43, 87,  3, 54, 63, 52,  7,  0, 73, 75,  5,
       83,  7, 86, 25, 64, 35, 85, 79, 76, 41, 51, 35, 16, 51, 41])

In [30]:
nd2 = nd.reshape(20,5)
nd2

array([[63, 48, 66, 13, 53],
       [70, 86, 68, 35, 69],
       [95, 53, 46, 80, 41],
       [93, 19,  1, 68, 56],
       [57, 13, 28, 25, 49],
       [ 1, 46, 73, 25, 45],
       [68, 16, 98, 23, 20],
       [78, 39, 19, 58, 10],
       [45,  5, 23, 87, 58],
       [18,  4, 59,  9, 22],
       [ 0, 71,  8, 63, 60],
       [54, 80, 46, 84, 57],
       [14, 58, 90, 27, 46],
       [12, 68, 31, 87, 42],
       [34, 62, 94, 25, 43],
       [87,  3, 54, 63, 52],
       [ 7,  0, 73, 75,  5],
       [83,  7, 86, 25, 64],
       [35, 85, 79, 76, 41],
       [51, 35, 16, 51, 41]])

In [31]:
nd3 = np.arange(5)
nd3

array([0, 1, 2, 3, 4])

In [32]:
nd2+nd3

array([[ 63,  49,  68,  16,  57],
       [ 70,  87,  70,  38,  73],
       [ 95,  54,  48,  83,  45],
       [ 93,  20,   3,  71,  60],
       [ 57,  14,  30,  28,  53],
       [  1,  47,  75,  28,  49],
       [ 68,  17, 100,  26,  24],
       [ 78,  40,  21,  61,  14],
       [ 45,   6,  25,  90,  62],
       [ 18,   5,  61,  12,  26],
       [  0,  72,  10,  66,  64],
       [ 54,  81,  48,  87,  61],
       [ 14,  59,  92,  30,  50],
       [ 12,  69,  33,  90,  46],
       [ 34,  63,  96,  28,  47],
       [ 87,   4,  56,  66,  56],
       [  7,   1,  75,  78,   9],
       [ 83,   8,  88,  28,  68],
       [ 35,  86,  81,  79,  45],
       [ 51,  36,  18,  54,  45]])

In [33]:
np.add(nd2,nd3)

array([[ 63,  49,  68,  16,  57],
       [ 70,  87,  70,  38,  73],
       [ 95,  54,  48,  83,  45],
       [ 93,  20,   3,  71,  60],
       [ 57,  14,  30,  28,  53],
       [  1,  47,  75,  28,  49],
       [ 68,  17, 100,  26,  24],
       [ 78,  40,  21,  61,  14],
       [ 45,   6,  25,  90,  62],
       [ 18,   5,  61,  12,  26],
       [  0,  72,  10,  66,  64],
       [ 54,  81,  48,  87,  61],
       [ 14,  59,  92,  30,  50],
       [ 12,  69,  33,  90,  46],
       [ 34,  63,  96,  28,  47],
       [ 87,   4,  56,  66,  56],
       [  7,   1,  75,  78,   9],
       [ 83,   8,  88,  28,  68],
       [ 35,  86,  81,  79,  45],
       [ 51,  36,  18,  54,  45]])

### 排序

In [35]:
nd

array([63, 48, 66, 13, 53, 70, 86, 68, 35, 69, 95, 53, 46, 80, 41, 93, 19,
        1, 68, 56, 57, 13, 28, 25, 49,  1, 46, 73, 25, 45, 68, 16, 98, 23,
       20, 78, 39, 19, 58, 10, 45,  5, 23, 87, 58, 18,  4, 59,  9, 22,  0,
       71,  8, 63, 60, 54, 80, 46, 84, 57, 14, 58, 90, 27, 46, 12, 68, 31,
       87, 42, 34, 62, 94, 25, 43, 87,  3, 54, 63, 52,  7,  0, 73, 75,  5,
       83,  7, 86, 25, 64, 35, 85, 79, 76, 41, 51, 35, 16, 51, 41])

In [36]:
np.sort(nd)

array([ 0,  0,  1,  1,  3,  4,  5,  5,  7,  7,  8,  9, 10, 12, 13, 13, 14,
       16, 16, 18, 19, 19, 20, 22, 23, 23, 25, 25, 25, 25, 27, 28, 31, 34,
       35, 35, 35, 39, 41, 41, 41, 42, 43, 45, 45, 46, 46, 46, 46, 48, 49,
       51, 51, 52, 53, 53, 54, 54, 56, 57, 57, 58, 58, 58, 59, 60, 62, 63,
       63, 63, 64, 66, 68, 68, 68, 68, 69, 70, 71, 73, 73, 75, 76, 78, 79,
       80, 80, 83, 84, 85, 86, 86, 87, 87, 87, 90, 93, 94, 95, 98])

In [ ]:
nd.sort()

In [40]:
nd

array([ 0,  0,  1,  1,  3,  4,  5,  5,  7,  7,  8,  9, 10, 12, 13, 13, 14,
       16, 16, 18, 19, 19, 20, 22, 23, 23, 25, 25, 25, 25, 27, 28, 31, 34,
       35, 35, 35, 39, 41, 41, 41, 42, 43, 45, 45, 46, 46, 46, 46, 48, 49,
       51, 51, 52, 53, 53, 54, 54, 56, 57, 57, 58, 58, 58, 59, 60, 62, 63,
       63, 63, 64, 66, 68, 68, 68, 68, 69, 70, 71, 73, 73, 75, 76, 78, 79,
       80, 80, 83, 84, 85, 86, 86, 87, 87, 87, 90, 93, 94, 95, 98])

#### 部分排序

In [43]:
nk = np.random.randint(0,10000,size=100)
nk

array([1432, 8188, 7575, 4187, 9853, 1888, 4377, 4496, 8850, 8873, 8008,
       1122, 4505, 4042, 6404,   96, 3995, 3271, 3980, 9757, 1626, 5297,
       8059,  220, 4286, 4036, 8433, 7494, 5979,  143, 9196, 5067,  970,
       1148,  940, 7814, 4653, 8026, 1961, 5040, 9622, 6031, 7597,  353,
       9239, 3933, 9496, 9817, 9500, 9564, 9288, 6829,  720, 8265, 7501,
       7369, 6202,  979, 3895, 8890, 8494, 9334,  442, 7591,  610, 4019,
        655, 5636, 4864, 5367, 8966, 7984, 6464, 9326, 2154, 2837, 1080,
       6465, 6843, 9816, 9817,  830, 1577, 9913, 2538, 6697, 4643, 6177,
       1748, 1172,  409, 2349, 4019, 5355, 3173, 7129, 4620, 7097,  415,
       4367])

In [44]:
np.partition(nk,kth = 5)  # 前五个为最小值

array([ 143,   96,  220,  353,  409,  415,  442,  655,  610,  720,  830,
       1122, 2538, 4042, 1577, 1748, 3995, 3271, 3980, 1432, 1626, 1080,
       2837, 1172, 4286, 4036, 2154, 2349, 4019, 4019, 1888, 3173,  970,
       1148,  940, 3895,  979, 4187, 1961, 3933, 4367, 6031, 7597, 9622,
       9239, 5040, 9496, 9817, 9500, 8188, 9288, 6829, 8026, 8265, 7501,
       7369, 6202, 4653, 7814, 8890, 8494, 9334, 5067, 7591, 9196, 5979,
       7494, 5636, 4864, 5367, 8966, 7984, 6464, 9326, 8433, 8059, 5297,
       6465, 6843, 9816, 9817, 9757, 6404, 9913, 4505, 6697, 4643, 6177,
       8008, 8873, 8850, 4496, 4377, 5355, 9853, 7129, 4620, 7097, 7575,
       9564])

In [45]:
np.partition(nk,kth = -5)[-5:] # 取出最大的5个数

array([9816, 9853, 9817, 9817, 9913])